name: Automerge PRs
on:
  pull_request:
    types: [labeled, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        if: contains(github.event.pull_request.user.login, 'dependabot')
      - name: Enable automerge
        if: ${{ !contains(github.event.pull_request.user.login, 'dependabot') }}
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
